Docker
openfisca/openfisca-france-data pull request #192
Opened 2021-03-18 17:18 UTC by benoit-cty

Bonjour !

I'm from the Leximpact team, I submit this PR as I thing it will help others to easily process ERFS FPR files.

#### New features

- Use Docker to install everything that is needed for ERFS FPR and process files.
- No change to the code, it is just a packaging of the manual process.

#### Technical changes

- Small addition in .gitignore to prevent commit of secret files (*.sas7bdat and *.h5) and the json generated by build-collection
- All others changes are in  docker/erfs folder. With a README in it.
- Tested on Ubuntu 20.04 with _Docker version 19.03.13, build cd8016b6bc_

2021-03-18 17:26 UTC, benoit-cty commented
@benjello Bonjour, la CI ne fonctionne pas car il n'arrive pas à récupérer le code, ceci ne semble pas avoir de lien avec la PR, que me conseille-tu ?
CC : @sandcha

2021-03-20 16:19 UTC, benjello commented
@benoit-cty ; franchement je ne sais pas ce qui ne va pas mais ce n'est pas bloquant pour moi. Donc on peut merger.
Faut juste updater la version.

2021-03-22 20:45 UTC, benoit-cty commented
Merci @benjello , je viens de push le bump de version.

2021-03-22 20:53 UTC, benjello commented
@sandcha @maukoquiroga si vous comprenez pour circleci râle alors qu'il y a deux c'est passé sans problème je suis preneur.

2021-03-22 21:42 UTC, benoit-cty commented
> @sandcha @maukoquiroga si vous comprenez pour circleci râle alors qu'il y a deux c'est passé sans problème je suis preneur.

Il y a bien une clef SSH de configuré sur Circle CI mais est-elle encore bien présente dans la config de Github ?

Côté CI il y a :
openfisca/openfisca-france-data user key :  ed:78:07:57:23:2b:40:98:47:d9:74:ed:59:85:d0:82

2021-04-13 11:59 UTC, sandcha commented
Sauf avis contraire, je tenterais une régénération de clef SSH entre CircleCI et GitHub pour tenter de débloquer le checkout. Ok pour toi @benjello ?

2021-04-24 00:25 UTC, sandcha commented
@benjello @benoit-cty Le bug de `checkout` a été résolu.
J'ai ajouté la clef SSH de déploiement CircleCI à ce dépôt (elle est [ici](https://github.com/openfisca/openfisca-france-data/settings/keys)).
> Plus d'information sur cette résolution à venir.

2021-04-24 06:59 UTC, benjello commented
Merci @sandcha. Reste à résoudre https://github.com/openfisca/openfisca-core/pull/1010.

2021-05-02 12:53 UTC, benoit-cty commented
openfisca/openfisca-core#1010 is now solved, what I have to do now?
Upgrade openfisca core in open fisca France data ?

2021-05-05 17:22 UTC, sandcha requested changes
Merci @benoit-cty pour cette documentation Docker 🙌 
J'ai malheureusement eu une erreur bloquante au `docker run`. Manquerait-il une étape au `README` ? 🤔 
Si ce n'est pas le cas, je te propose a minima d'indiquer que la configuration actuelle nécessiterait d'être sous Linux.

2021-05-05 17:22 UTC, sandcha commented on docker/erfs/README.md
> +- 4_ Launch Docker :
> Note mineure : à la différence du français, en anglais, [point d'espace avant les signes doubles](https://leconjugueur.lefigaro.fr/frponctuationtypographie.php). 😊

2021-05-05 17:22 UTC, sandcha commented on docker/erfs/README.md
> +docker run --rm -v $PWD/data:/opt/erfs/data openfisca-france-data-erfs
J'obtiens l'erreur suivante à l'exécution du docker run 😢 : 
```shell
...
Generate a flattened file consumable by openfisca...
/opt/erfs/entrypoint.sh: line 15:    13 Killed                  build-collection -c erfs_fpr -d -m -v -p $DATA_FOLDER
Traceback (most recent call last):
  File "/opt/openfisca-france-data/openfisca_france_data/erfs_fpr/input_data_builder/__init__.py", line 68, in <module>
    build(year = year, export_flattened_df_filepath = export_flattened_df_filepath)
  File "/opt/openfisca-france-data/openfisca_france_data/erfs_fpr/input_data_builder/__init__.py", line 32, in build
    preprocessing.build_merged_dataframes(year = year)
  File "/home/user/.local/lib/python3.7/site-packages/openfisca_survey_manager/temporary.py", line 38, in func_wrapper
    return func(*args, temporary_store = temporary_store, **kwargs)
  File "/opt/openfisca-france-data/openfisca_france_data/erfs_fpr/input_data_builder/step_01_preprocessing.py", line 30, in build_merged_dataframes
    eec_menage = survey.get_values(table = f"fpr_mrf{yr}e{yr}t4", ignorecase=True)
  File "/home/user/.local/lib/python3.7/site-packages/openfisca_survey_manager/surveys.py", line 182, in get_values
    assert self.hdf5_file_path is not None
AssertionError
mv: cannot stat '/opt/erfs/data/erfs_flat_*.h5': No such file or directory
```

**Qu'est-ce que j'ai fait pour en arriver là ?** 

Dans un environnement virtuel neuf, j'ai exécuté, `make install`, `make test` puis les étapes de ce `README`.

2021-05-05 17:22 UTC, sandcha commented on docker/erfs/README.md
> +# Generate flat data from ERFS-FPR with Docker
Ajouter une phrase au `README` à la racine du dépôt sur l'existence de cette documentation Docker pour la rendre découvrable ?

2021-05-06 17:14 UTC, sandcha commented on docker/erfs/README.md
> +docker run --rm -v $PWD/data:/opt/erfs/data openfisca-france-data-erfs
Avec @benoit-cty, nous avons épuisé nos premières pistes et serions intéressés par le test sur une autre machine. À tout hasard @benjello aurais-tu docker d'installé chez toi ?

2021-05-06 17:31 UTC, benoit-cty commented on docker/erfs/README.md
> +docker run --rm -v $PWD/data:/opt/erfs/data openfisca-france-data-erfs
On avait une piste sur le compte utilisateur qui n'aurait pas `.config/openfisca-survey-manager` mais ce n'était pas ça.

Le fait est que self.hdf5_file_path est à None dans Survey et qu'on ne comprend pas pourquoi.

Je pense qu'il faudrait des vérifications dans survey manager pour voir où est l'erreur.

2021-05-11 07:36 UTC, benoit-cty commented on docker/erfs/README.md
> +- 4_ Launch Docker :
Ah oui, merci.

2021-05-11 07:40 UTC, benoit-cty commented
Bonjour @benjello j'ai revu pas mal de choses, pourrais-tu tester de ton côté ?
La doc est là https://github.com/openfisca/openfisca-france-data/blob/docker/docker/README.md

Par contre, comme on est dans une branche, pour lancer le traitement il faut utiliser:
```
docker run --rm -v $PWD/docker/data:/opt/data \
 -v $PWD/openfisca_france_data:/opt/openfisca-france-data/openfisca_france_data \
 -v $PWD/docker:/opt/openfisca-france-data/docker \
 openfisca-france-data \
 /opt/openfisca-france-data/docker/erfs-fpr.sh
```
Ce qui monte le code local dans le conteneur.

2021-06-07 09:09 UTC, closed without merging

2021-06-07 09:36 UTC, benjello commented
@benoit-cty : j'ai fermé la PR mais puis-je aussi virer la branche sachant que j'ai intégré ce qui était sur leximpact

2021-06-07 11:18 UTC, benoit-cty commented
@benjello : Oui, je viens d'effacer la branche.